export const BACKORDER_OVERVIEW_SECTIONS = {
  backorder: {
    key: "hold_backorder",
    label: "Backorder",
    titleUpper: "BACKORDER",
    sub: "Orders on hold for inventory",
    icon: "localShipping",
    titleColor: "#dc2626",
    iconStyle: { background: "#fee2e2", color: "#dc2626" },
    routeName: "orders-backorder-list",
    pillVariant: "alert",
    countColumnLabel: "Orders",
    countField: "orders_count",
    emptyMessage: "No accounts with backorder orders.",
  },
  out_of_stock: {
    key: "out_of_stock",
    label: "Out of Stock",
    titleUpper: "OUT OF STOCK",
    sub: "Oversold units by account",
    icon: "gppBad",
    titleColor: "#b45309",
    iconStyle: { background: "#ffedd5", color: "#b45309" },
    routeName: "inventory",
    pillVariant: "alert",
    countColumnLabel: "Units",
    countField: "orders_count",
    emptyMessage: "No accounts with out-of-stock inventory.",
  },
};
