export const HOME_SUMMARY_CARDS = [
  {
    key: "ready_to_ship",
    label: "READY TO SHIP",
    icon: "inventoryBox",
    titleColor: "#1e3a8a",
    iconStyle: { background: "#dbeafe", color: "#1e3a8a" },
    valueSource: "totals",
    valueKey: "ready_to_ship",
    to: { name: "orders-fulfillment" },
  },
  {
    key: "on_hold",
    label: "ON-HOLD",
    icon: "hourglass",
    titleColor: "#b45309",
    iconStyle: { background: "#fef3c7", color: "#b45309" },
    valueSource: "totals",
    valueKey: "on_hold",
    to: { name: "orders-on-hold" },
  },
  {
    key: "hold_backorder",
    label: "BACKORDERS",
    icon: "gppBad",
    titleColor: "#dc2626",
    iconStyle: { background: "#fee2e2", color: "#dc2626" },
    valueSource: "sections",
    valueKey: "hold_backorder",
    to: { name: "orders-backorder" },
  },
  {
    key: "shipped",
    label: "SHIPPED TODAY",
    icon: "truck",
    titleColor: "#166534",
    iconStyle: { background: "#dcfce7", color: "#166534" },
    valueSource: "totals",
    valueKey: "shipped",
    to: { name: "orders-fulfillment" },
  },
  {
    key: "paused",
    label: "PAUSED",
    sub: "On-hold orders for paused accounts",
    icon: "pauseCircle",
    titleColor: "#6b7280",
    iconStyle: { background: "#f3f4f6", color: "#4b5563" },
    valueSource: "paused_on_hold_order_count",
    valueKey: null,
    to: { name: "client-accounts", query: { status: "paused" } },
  },
];
