export const HOME_SUMMARY_CARDS = [
  {
    key: "ready_to_ship",
    label: "READY TO SHIP",
    icon: "inventoryBox",
    titleColor: "#1e3a8a",
    iconStyle: { background: "#dbeafe", color: "#1e3a8a" },
    valueSource: "totals",
    valueKey: "ready_to_ship",
    to: { name: "orders-fulfillment" },
  },
  {
    key: "on_hold",
    label: "ON-HOLD",
    icon: "hourglass",
    titleColor: "#b45309",
    iconStyle: { background: "#fef3c7", color: "#b45309" },
    valueSource: "totals",
    valueKey: "on_hold",
    to: { name: "orders-on-hold" },
  },
  {
    key: "hold_backorder",
    label: "BACKORDERS",
    icon: "gppBad",
    titleColor: "#dc2626",
    iconStyle: { background: "#fee2e2", color: "#dc2626" },
    valueSource: "sections",
    valueKey: "hold_backorder",
    to: { name: "orders-out-of-stock" },
  },
  {
    key: "shipped",
    label: "SHIPPED TODAY",
    icon: "truck",
    titleColor: "#166534",
    iconStyle: { background: "#dcfce7", color: "#166534" },
    valueSource: "totals",
    valueKey: "shipped",
    to: { name: "orders-fulfillment" },
  },
  {
    key: "restocks",
    label: "RESTOCKS",
    sub: "Active restock rows",
    icon: "sync",
    titleColor: "#7c3aed",
    iconStyle: { background: "#f3e8ff", color: "#7c3aed" },
    valueSource: "restock_active_count",
    valueKey: null,
    to: { name: "inventory-restock" },
  },
  {
    key: "asn_pending",
    label: "ASN",
    sub: "Pending ASNs",
    icon: "asnDoc",
    titleColor: "#3730a3",
    iconStyle: { background: "#e0e7ff", color: "#3730a3" },
    valueSource: "totals",
    valueKey: "asn_pending",
    to: { name: "admin-asn-hub", query: { status: "pending" } },
  },
];
