export const SHIPPED_SUMMARY_CARDS = [
  {
    key: "today",
    label: "Shipped Today",
    titleUpper: "SHIPPED TODAY",
    sub: "Total Shipments",
    icon: "truck",
    titleColor: "#16a34a",
    iconStyle: { background: "#dcfce7", color: "#16a34a" },
  },
  {
    key: "yesterday",
    label: "Shipped Yesterday",
    titleUpper: "SHIPPED YESTERDAY",
    sub: "Total Shipments",
    icon: "truck",
    titleColor: "#16a34a",
    iconStyle: { background: "#dcfce7", color: "#16a34a" },
  },
  {
    key: "this_week",
    label: "Shipped This Week",
    titleUpper: "SHIPPED THIS WEEK",
    sub: "Mon – Sun",
    icon: "truck",
    titleColor: "#16a34a",
    iconStyle: { background: "#dcfce7", color: "#16a34a" },
  },
  {
    key: "last_week",
    label: "Shipped Last Week",
    titleUpper: "SHIPPED LAST WEEK",
    sub: "Mon – Sun",
    icon: "truck",
    titleColor: "#16a34a",
    iconStyle: { background: "#dcfce7", color: "#16a34a" },
  },
  {
    key: "this_month",
    label: "Shipped This Month",
    titleUpper: "SHIPPED THIS MONTH",
    sub: "Calendar month",
    icon: "truck",
    titleColor: "#16a34a",
    iconStyle: { background: "#dcfce7", color: "#16a34a" },
  },
];

export const SHIPPED_PANELS = [
  {
    key: "today",
    label: "Shipped Today",
    icon: "truck",
    iconStyle: { background: "#dcfce7", color: "#16a34a" },
    routeName: "orders-shipped-orders",
    datePreset: "today",
    metaSuffix: "(today)",
    pillVariant: "success",
    emptyMessage: "No shipments for today.",
  },
  {
    key: "yesterday",
    label: "Shipped Yesterday",
    icon: "truck",
    iconStyle: { background: "#dcfce7", color: "#16a34a" },
    routeName: "orders-shipped-orders",
    datePreset: "yesterday",
    metaSuffix: "(yesterday)",
    pillVariant: "success",
    emptyMessage: "No shipments for yesterday.",
  },
];
